### ISSUE TITLE
Typo in advancements

### ISSUE THREAD

**Issue by G-Stav** [MattCzyr/ExplorersCompass#1]
Parsing error loading custom advancement explorerscompass:explorers_compass_iron_bars: Unknown item tag 'minecraft:iron_bars'

Parsing error loading custom advancement explorerscompass:explorers_compass_cracked_stone_bricks: Unknown item tag 'minecraft:cracked_stone_bricks'

those two tags should be items.

**Comment by MattCzyr** [comment]
Fixed in version 1.1.1.
