### ISSUE TITLE
[Crash] Intermittent Startup Crash [v1.18.1-1.1.2-forge]

### ISSUE THREAD

**Issue by sdarkwell** [MattCzyr/ExplorersCompass#10]
**Hello,**

I often, but not always, experience the following crash starting Minecraft with Explorer's Compass v1.1.2 (Forge) for Minecraft v1.18.1.

**Attached is a log:**

- [latest.log](https://github.com/MattCzyr/ExplorersCompass/files/7874992/latest.log)

Interestingly, my girlfriend uses the exact same set of mods and configurations but doesn't experience the same crash.

The issue can be resolved by restarting Minecraft 1 - 3 more times.

**Hope this helps! Thank you and be well. :)**
- S.

**Comment by MattCzyr** [comment]
Should be fixed in version 1.2.3-forge.
