### ISSUE TITLE
Explorer compass will not look past 3000 blocks in Better minecraft plus

### ISSUE THREAD

**Issue by lSherozl** [MattCzyr/ExplorersCompass#14]
Exactly as the title says, no matter what distance I set the mod, it stays at a distance of 2700 some blocks, and sometimes the mod is very laggy, and takes forever just to look 1000 blocks

**Comment by MattCzyr** [comment]
This issue was due to the maximum configurable value for samples previously being set to 50000, which would be exhausted before the max radius was. In version 1.1.3 this has been changed to 1000000, so this should no longer be an issue with proper config values.
