### ISSUE TITLE
[1.18.1-Forge] Crash when opening Explorer's Compass.

### ISSUE THREAD

**Issue by Gbergz** [MattCzyr/ExplorersCompass#16]
Title^

**Minecraft**: 1.18.1
**Forge**: 38.0.75
**Explorer's Compass**: 1.1.2 | https://www.curseforge.com/minecraft/mc-mods/explorers-compass/files/3562000

**Crash-Report**: https://gist.github.com/Gbergz/001d744c4d37326a7122eaaae4cc10af

**Comment by MattCzyr** [comment]
Try using this beta file and let me know if the issue is resolved: [ExplorersCompass-1.18.1-1.1.3-forge-beta.jar](https://www.dropbox.com/s/5cnk4sck73r3ccz/ExplorersCompass-1.18.1-1.1.3-forge-beta.jar?dl=0)

**Comment by MattCzyr** [comment]
Just released version 1.18.1-1.1.3 which should fix this, feel free to reopen if it persists.
