### ISSUE TITLE
Null Pointer Exception when trying to use compass on server

### ISSUE THREAD

**Issue by MrHamid-am** [MattCzyr/ExplorersCompass#17]
**HELLO**
me and my friends love this mod, but when we try to use it on server-side, we get this exception and game crashes.

[crash-2022-02-24_22.16.06-client.txt](https://github.com/MattCzyr/ExplorersCompass/files/8142023/crash-2022-02-24_22.16.06-client.txt)

minecraft: 1.18.1-forge
Forge version: 39.0.79

**Comment by MattCzyr** [comment]
This should be fixed in version 1.18.1-1.1.3. Feel free to reopen if it persists.
