### ISSUE TITLE
crash when searching for structure that cant spawn in a certain dimension

### ISSUE THREAD

**Issue by benbenlaw** [MattCzyr/ExplorersCompass#2]
[crash-2021-07-15_18.23.27-server.txt](https://github.com/MattCzyr/ExplorersCompass/files/6825096/crash-2021-07-15_18.23.27-server.txt)
when searching for a structure in a dimension that it says it spawns in but doesnt game crashes

**Comment by MattCzyr** [comment]
Should be fixed as of version 1.1.2 for Forge and 2.0.1 for Fabric.
