### ISSUE TITLE
Not respecting maxRadius

### ISSUE THREAD

**Issue by tir38** [MattCzyr/ExplorersCompass#36]
I've bumped `maxRadius` both client-side and server-side. `maxRadius = 15000` However when I search for structures, I never find anything outside of a radius of 2000.

![2022-11-12_18 46 19 copy](https://user-images.githubusercontent.com/1980553/201499071-c92bdab1-2d7f-4949-a36b-dbbf759c27fb.png)

**Comment by MattCzyr** [comment]
Searches stop when either the max radius is reached, or the max number of samples have been taken. Looks like your `maxSamples` value is set to 50000, and this sample threshold is being reached long before the radius threshold is reached. If you want to search further than 2000 blocks, you'll have to raise `maxSamples` as well.
