### ISSUE TITLE
[1.16.5 Multiplayer] Visuals of the compass may spin when crossing some chunk borders

### ISSUE THREAD

**Issue by Kaleidio** [MattCzyr/ExplorersCompass#38]
This issue only occurs in multiplayer (both lan and dedicated servers) and does not occur in single player.  The compass points in the correct direction after the spin, it just so happens to spin every so often when crossing some chunk borders.  Not entirely sure why.

It only spins one revolution when it has this issue, leading me to believe the mod for whatever reason is trying to sync values on the client side even though the search has already completed.

**Comment by MattCzyr** [comment]
I think this was likely related to #49, so should have been fixed in versions 1.3.3-forge and 2.2.3-fabric. Feel free to reopen if not the case.
