### ISSUE TITLE
released a 1.20 mod for 1.20.1

### ISSUE THREAD

**Issue by Briatkee** [MattCzyr/ExplorersCompass#41]
you released a 1.20.1 for explorers Compas in 1.20 pls remove it or upload a 1.20 version 1.20.1 is useless

Replace mod 'Explorer's Compass' (explorerscompass) 1.20-2.2.2-fabric with any version that is compatible with:
minecraft 1.20

<html>Mod 'Explorer's<br>Compass' (explorerscompass) 1.20-2.2.2-fabric requires any version between 1.20.1 (inclusive) and 1.21- (exclusive) of 'Minecraft' (minecraft), but only the wrong version is present: 1.20!</html>

**Comment by MattCzyr** [comment]
Uploaded a fixed Fabric 1.20 file.
