### ISSUE TITLE
[1.20.4] Right-Click Instantly Crashes Game (BOTH COMPASSES)

### ISSUE THREAD

**Issue by codingmakesmyheadhurt** [MattCzyr/ExplorersCompass#58]
title says all. whenever you right click on either Nature's or the Explorer's Compass in 1.20.4, the game freezes and crashes. As my username would suggest, I know next to nothing about coding, so please use smoothbrain terminology with me. the launcher gives this error:

The game crashed whilst unexpected error
Error: java.lang.IncompatibleClassChangeError: class com.chaosthedude.explorerscompass.gui.TransparentTextField overrides final method net.minecraft.class_339.method_25394(Lnet/minecraft/class_332;IIF)V

The logs I have show a lot of mods I use at the bottom, but I tested without any other non-essential mods and it crashed the exact same way with the same error code. Nonetheless, I figured I'd include the modded crash report since it might be worth looking at any potential incompatibilities with something fundamental. I didn't see anything in the report that would indicate another mod interfering, but like I said I'm not a coder at all and I really only have a _very_ basic understanding of how you magicians make stuff work.

[crash-2023-12-22_14.10.30-client.txt](https://github.com/MattCzyr/ExplorersCompass/files/13756251/crash-2023-12-22_14.10.30-client.txt)

**Comment by MattCzyr** [comment]
I just released Forge and Fabric versions specifically for 1.20.4, use those instead.
