### ISSUE TITLE
Changing radius in config does nothing in game

### ISSUE THREAD

**Issue by iamchrisllaga** [MattCzyr/ExplorersCompass#6]
I change the radius in the config file. Start the game, use the compass, still says that the search radius is 2750.

**Comment by MattCzyr** [comment]
The compass will report the radius that _was_ searched, which can be limited by both the configured search radius and max samples. I suspect the max number of samples is being taken before the max search radius is reached, so the compass reports that the same radius was searched. I recommend raising the max samples in the config.
