### ISSUE TITLE
[1.20.5] NeoForge and Fabric adding a c:hidden_from_locator_selection structure tag

### ISSUE THREAD

**Issue by TelepathicGrunt** [MattCzyr/ExplorersCompass#63]
As part of the tag unification PRs here:
https://github.com/FabricMC/fabric/pull/3310
https://github.com/neoforged/NeoForge/pull/135

Both Fabric and NeoForge will add a `c:hidden_from_locator_selection` structure tag to allow structure makers specify if their structure should not be locatable with modded items/abilities such as Explorer's Compass. This could be for balance reasons or technical reasons or whatever. Especially technical reasons as Terralith has some dummy structures they use for allowing vanilla Explorer Map items to "point" to one of their biomes since the map item cannot locate biomes directly. This dummy structure is something they would like to hide from world viewers and not be locatable with Explorer's Compass (instead Nature's Compass should be used by the player for finding the biomes)

This is just a heads up on this upcoming convention tag that you might be interested in having your mod check for to know what structure to not allow users to locate with your item.

**Comment by MattCzyr** [comment]
Implemented in 3.0.1-neoforge and 2.2.4-fabric.
