### ISSUE TITLE
Can't craft on Fabric version 1.21 (mod version 2.2.4)

### ISSUE THREAD

**Issue by w1zlm** [MattCzyr/ExplorersCompass#66]
Hey Chaosyr. I just download this mod for Fabric on version 1.21 (mod version 2.2.4) and the craft shown in a picture doesnt work, even checking the recipe on EMI (alternative to JEI) just doesn't show anything. I disabled every other mod but i still couldn't craft it. Can you please fix this bug?
![image](https://github.com/MattCzyr/ExplorersCompass/assets/103192716/ef17c4a9-24ef-4c6e-ae3a-30fd0e72901e)

**Comment by MattCzyr** [comment]
Fixed in 2.2.5.
