### ISSUE TITLE
Can't blacklist any structure

### ISSUE THREAD

**Issue by DeadGator** [MattCzyr/ExplorersCompass#79]
I tried configuring the blacklist  in game with the help of the mod configured , and outside the game in the text file.

For example i want to blacklist  the impaled icebreaker from irons spellbooks. I press add, write ''irons_spellbooks:impaled_icebreaker'' then i simply can't press the ''apply'' button, only to go back and my changes aren't saved. I think i'm doing something wrong. I even experimented with other structures even vanilla structures and they don't work.

I tried without the " ", i tried irons_spellbooks:*impaled_icebreaker*, i tried with '','' at the end of the structure, i tried with [    ] and nothing works in game. When i went into the config folder to edit it from outside the game and entered the structure's name and launch the game, the font and every letter and number in my game looked like : [][][][][][][][][][] so i had to delete what i wrote for it to go back to normal.

I even attempted to write exactly what the examples told me when the blacklist button was hovered, not even minecraft:endcity worked

**Comment by MattCzyr** [comment]
I'm not sure which in-game config editor you're using, so I can't speak on that. I recommend you edit the config file outside of the game in something like Notepad or Notepad++ so you can ensure that the formatting is correct. The `structureBlacklist` property should be formatted like this:

```
structureBlacklist = ["minecraft:stronghold", "minecraft:endcity", "irons_spellbooks:impaled_icebreaker"]
```

**Comment by DeadGator** [comment]
Late reply but works now, for some reason you can only configure it outside the game, i was using the ''configured'' by mrcrayfish to attempt to config the mod.
